version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: quarterly
    time: "04:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: mysql:mysql-connector-java
    versions:
    - 8.0.23
  - dependency-name: org.apache.maven.shared:maven-common-artifact-filters
    versions:
    - 3.1.1

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: quarterly
    time: "04:00"
  open-pull-requests-limit: 99

- package-ecosystem: "devcontainers"
  directory: "/"
  schedule:
    interval: quarterly
    time: "04:00"
