language: java

# We need Java 8, even though the source code is still Java 6, 
# because Checkstyle during build is Java 7+ only; and we use
# OpenJDK instead of Oracle JDK because ya all should only
# ever use OpenJDK!  (And get Red Hat's support for it, if
# you use it professionally.)
jdk: 
  - openjdk8

# Do *NOT* cache, see https://github.com/vorburger/MariaDB4j/issues/262
# cache:
#  directories:
#  - $HOME/.m2
#  - .mvn

before_install:
# TODO uncomment this when raising a PR to fix https://github.com/vorburger/MariaDB4j/issues/484
#  - mvn -f DBs/pom.xml clean install

# Must explicitly invoke checkstyle-check because package does not include it
script: mvn package -B -V
